language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
      install:
        - pip install zigate[dev] homeassistant
      script:
        - tox
        - python3 -m unittest
    - python: 3.6
      env: TOXENV=py36
      install:
        - pip install zigate[dev] homeassistant
      script:
        - tox
        - python3 -m unittest
    - python: 3.7
      env: TOXENV=py37
      install:
        - pip install zigate[dev] homeassistant
      script:
        - tox
        - python3 -m unittest
    - python: 3.8
      env: TOXENV=py38
      install:
        - pip install zigate[dev] homeassistant
      script:
        - tox
        - python3 -m unittest
